spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsinjo_${ENV:dev}
    username: ${DB_USERNAME:tsinjo}
    password: ${DB_PASSWORD:tsinjo}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true