spring:
  profiles:
    active: ${ENV:dev}
  application:
    name: tsinjo-std21001
  datasource:
    url: jdbc:postgresql://localhost:5432/tsinjo_${ENV:dev}
    username: ${DB_USERNAME:tsinjo}
    password: ${DB_PASSWORD:tsinjo}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: ${PORT:8080}

logging:
  level:
    com.hei.tsinjo: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

vola:
  api:
    base-url: https://tb5rnkxhmpeui22aebnvpchlky0kzffi.lambda-url.eu-west-3.on.aws/
    key: 13e46640-889f-4d59-b45b-62f4e9dd3830
    timeout: 30s
    retry:
      max-attempts: 10
      delay: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always