spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tsinjo_dev
    username: tsinjo
    password: tsinjo
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
vola:
  api:
    base-url: http://localhost:8080/vola-api
    key: 13e46640-889f-4d59-b45b-62f4e9dd3830
